package com.scholarsync.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.foundation.layout.statusBars
import androidx.compose.foundation.layout.windowInsetsPadding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.Build
import androidx.compose.material.icons.filled.Lightbulb
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.scholarsync.ui.theme.*

@Composable
fun HelpTroubleshootingScreen(onBack: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Gray100)
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .background(Color.White)
                .drawBehind {
                    drawLine(
                        color = Gray100,
                        start = Offset(0f, size.height),
                        end = Offset(size.width, size.height),
                        strokeWidth = 1f
                    )
                }
        ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .windowInsetsPadding(WindowInsets.statusBars)
                .padding(horizontal = 24.dp)
                .padding(top = 6.dp, bottom = 6.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = onBack) {
                Icon(Icons.Default.ArrowBack, contentDescription = "Back", tint = Primary)
            }
            Text(
                text = "Troubleshooting",
                fontSize = 18.sp,
                fontWeight = FontWeight.SemiBold,
                color = Primary,
                modifier = Modifier.weight(1f)
            )
            Box(modifier = Modifier.size(48.dp))
        }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(16.dp)
        ) {
            Text(
                text = "Common issues and tips to use the app more efficiently.",
                fontSize = 14.sp,
                color = TextSecondary,
                lineHeight = 22.sp,
                modifier = Modifier.padding(bottom = 20.dp)
            )

            Text(
                text = "COMMON ISSUES",
                fontSize = 12.sp,
                fontWeight = FontWeight.Bold,
                color = Gray400,
                letterSpacing = 1.sp,
                modifier = Modifier.padding(bottom = 12.dp)
            )

            TroubleshootItem(
                icon = Icons.Default.Build,
                title = "Feed or Discover not loading",
                description = "Check your internet connection and ensure the app has network access. If you use a custom backend, verify the URL in Settings and that the server is running. Pull to refresh to retry."
            )
            TroubleshootItem(
                icon = Icons.Default.Build,
                title = "Summaries not showing",
                description = "Summaries are generated by our servers. If they don’t appear, the backend may be busy or your API key may be missing or invalid. Check Settings for API configuration and try again later."
            )
            TroubleshootItem(
                icon = Icons.Default.Build,
                title = "Alerts not firing",
                description = "Make sure you’ve created a project and enabled alerts. Overlap and new-paper alerts run on a schedule; allow up to 24 hours for the first run. Check that notifications are enabled for the app."
            )
            TroubleshootItem(
                icon = Icons.Default.Build,
                title = "Login or session issues",
                description = "If you’re signed out unexpectedly, sign in again. Clear app data only if needed; you’ll need to log in and reconfigure profile and API settings afterward."
            )

            Spacer(modifier = Modifier.height(24.dp))
            Text(
                text = "USE THE APP EFFICIENTLY",
                fontSize = 12.sp,
                fontWeight = FontWeight.Bold,
                color = Gray400,
                letterSpacing = 1.sp,
                modifier = Modifier.padding(bottom = 12.dp)
            )

            TroubleshootItem(
                icon = Icons.Default.Lightbulb,
                title = "Keep your profile updated",
                description = "Your interests and topics drive the feed. Update them in profile setup or Edit Profile so recommendations stay relevant."
            )
            TroubleshootItem(
                icon = Icons.Default.Lightbulb,
                title = "Use folders in Library",
                description = "Organize saved papers into folders by project or topic so you can find them quickly."
            )
            TroubleshootItem(
                icon = Icons.Default.Lightbulb,
                title = "Set up alerts once",
                description = "Configure overlap and new-paper alerts for your projects; you’ll get notifications without checking the app constantly."
            )

            Spacer(modifier = Modifier.height(32.dp))
        }
    }
}

@Composable
private fun TroubleshootItem(
    icon: ImageVector,
    title: String,
    description: String
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 6.dp),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
        border = androidx.compose.foundation.BorderStroke(1.dp, Primary.copy(alpha = 0.08f))
    ) {
        Row(
            modifier = Modifier.padding(16.dp),
            verticalAlignment = Alignment.Top
        ) {
            Icon(
                icon,
                contentDescription = null,
                tint = AccentTeal,
                modifier = Modifier.size(24.dp)
            )
            Spacer(modifier = Modifier.width(12.dp))
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = title,
                    fontSize = 15.sp,
                    fontWeight = FontWeight.SemiBold,
                    color = Primary
                )
                Spacer(modifier = Modifier.height(4.dp))
                Text(
                    text = description,
                    fontSize = 13.sp,
                    color = TextSecondary,
                    lineHeight = 20.sp
                )
            }
        }
    }
}
